config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

    scope "(:locale)", locale: /en|es/ do  
        #Personal links
        get '/books/my', to: 'books#my'

        resources :paymments
        resources :books
        resources :pictures
        resources :reports
        resources :comments
        resources :notifications
        resources :ranks
        resources :orders
        resources :posts
        resources :categories
        resources :addresses
        resources :genders
        resources :users
        resources :cities
        resources :countries
        resources :conversations, only: [:index, :show, :new, :create] do
            member do
              post :reply
              post :trash
              post :untrash
            end
        end
        # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
        root to: "web#index"



        #AJAX 
        get '/cities_country/:id', to: 'cities#index', as: 'cities_country'
        post '/cities_country', to: 'cities#index'
        get '/books/:id/like', to: 'books#like' #like book
    end
  
  
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :rank
  belongs_to :paymment
  belongs_to :book
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:user_id, :rank_id, :paymment_id, :book_id, :caracter, :content, :checked)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :rank_id %>
    <%= f.text_field :rank_id %>
  </div>

  <div class="field">
    <%= f.label :paymment_id %>
    <%= f.text_field :paymment_id %>
  </div>

  <div class="field">
    <%= f.label :book_id %>
    <%= f.text_field :book_id %>
  </div>

  <div class="field">
    <%= f.label :caracter %>
    <%= f.text_field :caracter %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :checked %>
    <%= f.check_box :checked %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Rank</th>
      <th>Paymment</th>
      <th>Book</th>
      <th>Caracter</th>
      <th>Content</th>
      <th>Checked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.user.name %></td>
        <td><%= notification.rank %></td>
        <td><%= notification.paymment %></td>
        <td><%= notification.book.name if notification.book.present? %></td>
        <td><%= notification.caracter %></td>
        <td><%= notification.content %></td>
        <td><%= notification.checked %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notification.user %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @notification.rank %>
</p>

<p>
  <strong>Paymment:</strong>
  <%= @notification.paymment %>
</p>

<p>
  <strong>Book:</strong>
  <%= @notification.book %>
</p>

<p>
  <strong>Caracter:</strong>
  <%= @notification.caracter %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<p>
  <strong>Checked:</strong>
  <%= @notification.checked %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>